### ISSUE TITLE
[BUG] YouTube Timestamp Anchor URL

### ISSUE THREAD

**Issue by sovalyeler** [cyfung1031/Tabview-Youtube#28] opened 2024-01-02 21:40 UTC
First of all I want to thank you for this script.
My problem is that the script causes Youtube to ignore timestamp anchor links.
e.g. https://www.youtube.com/watch?v=TLnUJzueBOQ#t=38s
(Edge 120.0.2210.91)

**Comment by cyfung1031** [comment] 2024-01-02 23:52
Fixed now.

By the way, `#t=xxx` is the old way for the timestamp. The current way is `&t=xxx`
You can really feel the difference that, `#t=38s` will take some time to play at the 38s after the video is being played from the start.
`&t=38s` is the official and current way to directly load from 38s.

**Closed as completed** 2024-01-03 00:59 UTC

**Comment by cyfung1031** [comment] 2024-01-03 05:49
@sovalyeler  I have updated that script and hope the author will update it. 

See https://greasyfork.org/scripts/35760-yt-url-at-time/discussions/220601

https://github.com/cyfung1031/userscript-supports/raw/main/revised-35760-yt-url-at-time.user.js

**Comment by cyfung1031** [comment] 2024-01-16 06:37
> Just recently realized that Youtube ignores precise timestamp(Alt+Click) w/ "&t=". Ex: https://www.youtube.com/watch?v=4Wg-RQpcpUU&t=115.735294 Upon refreshing the page, timestamp gets removed. Can you update the script please?

I have checked that this is not caused by my script.
From my understanding, `&t=115.735294` is not a recognized format used in YouTube.
it should be an integer or with `s` (`&t=115` or `&t=115s`)
